### ISSUE TITLE
Send notification to client who made the message on updates

### ISSUE THREAD

**Issue by DanTheManGude** [DanTheManGude/tech-boy-assistance#6]
- [x] ~change message to include a uid~
- [x] when a client logs in, update the name field for their account
- [x] update the UI to show 'notification access' and 'update fcm' token button
  - [x] maybe these can be combined or determined to be hidden
- [x] change the ui of messages for client to see status
- [x] change messages ui for admin to add status field
- [x] add server-less function for "updates" to send notification
  - [x] ~deleting counts as an update~
- [x] status of message is stored in the db
- [x] ~when a message is deleted then there is a "deletedCount" in the account~
- [x] each message has an "unread" property
  - [x] when the client loads the app 
    - [x] all messages become read
    - [x] ~deleted count is removed~
    - [x] clears app badge
- [x] a notification still includes the absolute value of what the app badge should use
  - [x] client is how many unread messages there are plus deleted count
  - [x] admin is how many messages have not been "ACK"ed (the status of new messages is "unread")
- [x] client can delete messages
  - [x] sends notification to admin and updates app badge

**Comment by DanTheManGude** [comment]
Updates will include:
- "ACK"
- "In progress"
- "Completed"

@emt1166 what do you think of these status updates?

**Comment by emt1166** [comment]
I think that would be helpful and would promote more user interaction.
